---
version: '3'

tasks:
  decrypt:
    desc: Decrypt .env using SOPS
    preconditions:
      - test -f .tokens.enc
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .tokens.enc > .tokens
  encrypt:
    desc: Encrypt .env using SOPS
    preconditions:
      - test -f .tokens
    cmds:
      - sops -e --input-type dotenv --output-type dotenv .tokens > .tokens.enc
  deps:
    desc: Install dependencies
    cmds:
      - sudo apt install -y stow
  install:
    desc: Install dotfiles
    cmds:
      - stow -v -t ~/ .
  restow:
    desc: Reinstall dotfiles
    cmds:
      - stow -v -R -t ~/ .
  delete:
    desc: Delete
    cmds:
      - stow -v -D -t ~/ .
  test:
    desc: Test
    cmds:
      - stow -n -v -t ~/ .
  default:
    cmds:
      - task -l
    silent: true
