---
version: '3'

tasks:
  deps:
    desc: Install dependencies
    cmds:
      - sudo apt install stow -y
  bootstrap:
    desc: Bootstrap dotfiles
    cmds:
      - task: decrypt
      - task: install
  decrypt:
    desc: Decrypt .env using SOPS
    preconditions:
      - test -f ./bash/.tokens.enc
    cmds:
      - sops -d --input-type dotenv --output-type dotenv ./bash/.tokens.enc > ./bash/.tokens
  encrypt:
    desc: Encrypt .env using SOPS
    preconditions:
      - test -f ./bash/.tokens
    cmds:
      - sops -e --input-type dotenv --output-type dotenv ./bash/.tokens > ./bash/.tokens.enc
  deps:
    desc: Install dependencies
    cmds:
      - sudo apt install -y stow
  test:
    desc: Stow each dotfile folder individually
    cmds:
      - for d in */; do if [[ "$d" != ".git/" && "$d" != ".github/" ]]; then stow -n -v --adopt -t ~/ "${d%/}"; fi; done
  install:
    desc: Stow each dotfile folder individually
    cmds:
      - for d in */; do stow -v --adopt -t ~/ "${d%/}"; git restore "${d%/}"; done
  restow:
    desc: Restow each dotfile folder individually
    cmds:
      - for d in */; do if [[ "$d" != ".git/" && "$d" != ".github/" ]]; then stow -v -R --adopt -t ~/ "${d%/}"; git restore "${d%/}";fi; done
  delete:
    desc: Delete each dotfile folder individually
    cmds:
      - for d in */; do if [[ "$d" != ".git/" && "$d" != ".github/" ]]; then stow -v -D --adopt -t ~/ "${d%/}"; fi; done
  nuke:
    desc: Nuke existing files
    cmds:
      - rm ~/.config/micro/settings.json
  default:
    cmds:
      - task -l
    silent: true
