#!/bin/bash
################################################################################
#
# libbash
# ----------------
# Library of bash functions
#
# @author Nicholas Wilde, 0x08b7d7a3
# @date 08 Mar 2021
# @version 0.0.2
#
################################################################################

set -e
set -o pipefail

# set variables
declare -r TRUE=0
declare -r FALSE=1
declare -r PASSWD_FILE=/etc/passwd

##################################################################
# Purpose: Converts a string to lower case
# Arguments:
#   $1 -> String to convert to lower case
# https://bash.cyberciti.biz/guide/Shell_functions_library
##################################################################
function to_lower() { tr '[:upper:]' '[:lower:]'<<<"${*}"; }

function to_upper() { tr '[:lower:]' '[:upper:]'<<<"${*}"; }

##################################################################
# Purpose: Return true if script is executed by the root user
# Arguments: none
# Return: True or False
# https://bash.cyberciti.biz/guide/Shell_functions_library
##################################################################
function is_root() { [ "$(id -u)" -eq 0 ] && return $TRUE || return $FALSE; }

##################################################################
# Purpose: Return true $user exits in /etc/passwd
# Arguments: $1 (username) -> Username to check in /etc/passwd
# Return: True or False
# https://bash.cyberciti.biz/guide/Shell_functions_library
##################################################################
function is_user_exits() { grep -q "^${1}" $PASSWD_FILE && return $TRUE || return $FALSE; }

# Check is variable is null
function is_null() { [ -z "$1" ]; }

# Check if variable is set
# Returns false if empty
function is_set() { [ -n "${1}" ]; }

# Check if directory exists
function dir_exists() { [ -d "${1}" ]; }

# Check if file exists
function file_exists() { [ -f "${1}" ]; }

# Check if command exists
function command_exists() { command -v "${1}" &> /dev/null; }

# Strip the file extension: foo.tar.gz -> foo
function strip_ext() { echo "${1%%.*}"; }

function get_last() { echo "${1: -1}"; }

function trim_last() { echo "${1::-1}"; }

function get_first() { echo "${1::1}"; }

function trim_first() { echo "${1: 1}"; }

##################################################################
# Purpose: Checks if the first argument contains the second
# Arguments:
#   $1 -> Long string to search in
#   $2 -> String to search for
# https://stackoverflow.com/a/229606/1061279
##################################################################
function contains() { [[ "$1" == *"$2"* ]]; }

##################################################################
# Purpose: Generate a random string of a certain length
# Arguments:
#   $1 Default:64 -> Length of string to return
##################################################################
function random() { < /dev/urandom tr -dc 'a-zA-Z0-9' | fold -w "${1:-64}" | head -n 1; }
