#!/bin/bash
# Library of bash functions

set -e
set -o pipefail

# set variables
declare -r TRUE=0
declare -r FALSE=1
declare -r PASSWD_FILE=/etc/passwd

##################################################################
# Purpose: Return true if script is executed by the root user
# Arguments: none
# Return: True or False
# https://bash.cyberciti.biz/guide/Shell_functions_library
##################################################################
function is_root() {
  [ "$(id -u)" -eq 0 ] && return $TRUE || return $FALSE
}

##################################################################
# Purpose: Return true $user exits in /etc/passwd
# Arguments: $1 (username) -> Username to check in /etc/passwd
# Return: True or False
# https://bash.cyberciti.biz/guide/Shell_functions_library
##################################################################
function is_user_exits() {
  local u="$1"
  grep -q "^${u}" $PASSWD_FILE && return $TRUE || return $FALSE
}
