#!/bin/bash
# Library of bash functions

set -e
set -o pipefail

# set variables
declare -r TRUE=0
declare -r FALSE=1
declare -r PASSWD_FILE=/etc/passwd

##################################################################
# Purpose: Converts a string to lower case
# Arguments:
#   $1 -> String to convert to lower case
# https://bash.cyberciti.biz/guide/Shell_functions_library
##################################################################
function to_lower() {
    local str="$*"
    local output
    output=$(tr '[:upper:]' '[:lower:]'<<<"${str}")
    printf "%s\n" "${output}"
}

##################################################################
# Purpose: Return true if script is executed by the root user
# Arguments: none
# Return: True or False
# https://bash.cyberciti.biz/guide/Shell_functions_library
##################################################################
function is_root() {
  [ "$(id -u)" -eq 0 ] && return $TRUE || return $FALSE
}

##################################################################
# Purpose: Return true $user exits in /etc/passwd
# Arguments: $1 (username) -> Username to check in /etc/passwd
# Return: True or False
# https://bash.cyberciti.biz/guide/Shell_functions_library
##################################################################
function is_user_exits() {
  local u="$1"
  grep -q "^${u}" $PASSWD_FILE && return $TRUE || return $FALSE
}

# Check is variable is null
function is_null {
  [ -z "$1" ]
}

# Check if directory exists
function dir_exists(){
  [ -d "${1}" ]
}

# Check if file exists
function file_exists(){
  [ -f "${1}" ]
}

# Check if command exists
function command_exists(){
  command -v "${1}" &> /dev/null
}

# Check if variable is set
# Returns false if empty
function is_set(){
  [ -n "${1}" ]
}
