#!/bin/bash
################################################################################
#
# libbash
# ----------------
# Library of bash functions
#
# @author Nicholas Wilde, 0x08b7d7a3
# @date 08 Mar 2021
# @version 0.0.3
#
################################################################################

set -e
set -o pipefail

# set variables
declare -r TRUE=0
declare -r FALSE=1
declare -r PASSWD_FILE=/etc/passwd

##################################################################
# Usage: echo "$(color::green)foo bar$(color::clr)"
# https://en.wikipedia.org/wiki/ANSI_escape_code
##################################################################
function color::black() { printf "\e[30m"; }
function color::red() { printf "\e[31m"; }
function color::green() { printf "\e[32m"; }
function color::yellow() { printf "\e[33m"; }
function color::blue() { printf "\e[34m"; }
function color::magenta() { printf "\e[35m"; }
function color::cyan() { printf "\e[36m"; }
function color::white() { printf "\e[37m"; }
function color::gray() { printf "\e[90m"; }
function color::bold() { printf "\e[1m"; }
function color::clr() { printf "\e[0m"; }
function color::brightred() { printf "\e[91m"; }
function color::brightgreen() { printf "\e[92m"; }
function color::brightyellow() { printf "\e[93m"; }
function color::brightblue() { printf "\e[94m"; }
function color::brightmagenta() { printf "\e[95m"; }
function color::brightcyan() { printf "\e[96m"; }
function color::brightwhite() { printf "\e[97m"; }

##################################################################
# Purpose: Return true $user exits in /etc/passwd
# Arguments: $1 (username) -> Username to check in /etc/passwd
# Return: True or False
# https://bash.cyberciti.biz/guide/Shell_functions_library
##################################################################
function check::is_user_exits() { grep -q "^${1}" $PASSWD_FILE && return $TRUE || return $FALSE; }

# Check if directory exists
function check::dir_exists() { [ -d "${1}" ]; }

# Check if file exists
function check::file_exists() { [ -f "${1}" ]; }

# Strip the file extension: foo.tar.gz -> foo
function strip_ext() { echo "${1%%.*}"; }
function get_last() { echo "${1: -1}"; }
function trim_last() { echo "${1::-1}"; }
function get_first() { echo "${1::1}"; }
function trim_first() { echo "${1: 1}"; }

##################################################################
# Purpose: Generate a random string of a certain length
# Arguments:
#   $1 Default:64 -> Length of string to return
##################################################################
function string::random() { < /dev/urandom tr -dc 'a-zA-Z0-9' | fold -w "${1:-64}" | head -n 1; }
